apiVersion: v1
kind: Pod
metadata:
  name: healthcarepod
spec:
  containers:
    - image: reg.rconnect.org/k8s-virtual-repo/healthcare:2.0
      name: healthcare
      ports:
        - containerPort: 8081
          name: http
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /actuator/health/liveness
          port: 8081
        initialDelaySeconds: 15
        timeoutSeconds: 5
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /actuator/health/readiness
          port: 8081
        initialDelaySeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
