apiVersion: v1
kind: Pod
metadata:
  name: healthcarepod
  labels:
    app: healthcare
    environment: production
spec:
  containers:
    - image: reg.rconnect.org/k8s-virtual-repo/healthcare:2.0
      name: healthcare
      ports:
        - containerPort: 8081
          name: http
          protocol: TCP     
      env:
        - name: datasource.username
          valueFrom:
            secretKeyRef:
              name: healthdbcred
              key: username
        - name: datasource.password
          valueFrom:
            secretKeyRef:
              name: healthdbcred
              key: password
     