server:
  port: 8081
spring:
  application:
    name: covido  
  mvc:
    view:
      prefix: /
      suffix: .html
      
management:
  endpoints:
    web:
      exposure:
        include:        
        - health    
  endpoint:
    health:
      probes:
        enabled: true
              